services:
  mongodb:
    image: mongo:7.0
    container_name: formagent-mongodb
    restart: unless-stopped
    network_mode: host
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-formagent}
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: formagent-backend
    restart: unless-stopped
    network_mode: host
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=${BACKEND_PORT:-5000}
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@localhost:27017/${MONGO_DATABASE:-formagent}?authSource=admin
      - FRONTEND_URL=http://localhost:3000

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: formagent-frontend
    restart: unless-stopped
    network_mode: host
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000
      - VITE_WS_URL=ws://localhost:5000
      - PORT=${FRONTEND_PORT:-3000}

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local