version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: formagent-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-formagent}
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - formagent-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  mongo-express:
    image: mongo-express:1.0.2
    container_name: formagent-mongo-express
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD:-password123}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    networks:
      - formagent-network

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: formagent-backend
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password123}@mongodb:27017/${MONGO_DATABASE:-formagent}?authSource=admin
      - FRONTEND_URL=http://localhost:3000
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - formagent-network
    command: npm run dev

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  formagent-network:
    driver: bridge